export const COLOR_SELECCIONADO = 'COLOR_SELECCIONADO';

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

// Inicia los types de producto

export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR';

export const FILTRAR_PRODUCTOS_EXITO = 'FILTRAR_PRODUCTOS_EXITO';
export const FILTRAR_PRODUCTOS_ERROR = 'FILTRAR_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_SELECCIONADO = 'OBTENER_PRODUCTO_SELECCIONADO';
export const PRODUCTO_SELECCIONADO_EXITO = 'PRODUCTO_SELECCIONADO_EXITO';
export const PRODUCTO_SELECCIONADO_ERROR = 'PRODUCTO_SELECCIONADO_ERROR';
export const LIMPIAR_PRODUCTOS = 'LIMPIAR_PRODUCTOS';



// inicio carrito
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const AGREGAR_PRODUCTO_CARRO_ERROR = 'AGREGAR_PRODUCTO_CARRO_ERROR';
export const ADD_ONE_TO_CART = "ADD_ONE_TO_CART";
export const GET_TOTAL = "GET_TOTAL";
export const ADD_MANY_TO_CART = "ADD_MANY_TO_CART";


//Stock
export const AGREGAR_PRODUCTO_STOCK = 'AGREGAR_PRODUCTO_STOCK';
export const AGREGAR_PRODUCTO_STOCK_EXITO = 'AGREGAR_PRODUCTO_STOCK_EXITO';
export const AGREGAR_PRODUCTO_STOCK_ERROR = 'AGREGAR_PRODUCTO_STOCK_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS_STOCK = 'COMENZAR_DESCARGA_PRODUCTOS_STOCK';
export const DESCARGA_PRODUCTOS_STOCK_EXITO = 'DESCARGA_PRODUCTOS_STOCK_EXITO';
export const DESCARGA_PRODUCTOS_STOCK_ERROR = 'DESCARGA_PRODUCTOS_STOCK_ERROR';

export const OBTENER_PRODUCTO_STOCK_ELIMINAR = 'OBTENER_PRODUCTO_STOCK_ELIMINAR';
export const PRODUCTO_STOCK_ELIMINADO_EXITO = 'PRODUCTO_STOCK_ELIMINADO_EXITO';
export const PRODUCTO_STOCK_ELIMINADO_ERROR = 'PRODUCTO_STOCK_ELIMINADO_ERROR';

export const OBTENER_PRODUCTO_STOCK_EDITAR = 'OBTENER_PRODUCTO_STOCK_EDITAR';
export const COMENZAR_EDICION_PRODUCTO_STOCK = 'COMENZAR_EDICION_PRODUCTO_STOCK';
export const PRODUCTO_STOCK_EDITADO_EXITO = 'PRODUCTO_STOCK_EDITADO_EXITO';
export const PRODUCTO_STOCK_EDITADO_ERROR = 'PRODUCTO_STOCK_EDITADO_ERROR';

export const FILTRAR_PRODUCTOS_STOCK_EXITO = 'FILTRAR_PRODUCTOS_STOCK_EXITO';
export const FILTRAR_PRODUCTOS_STOCK_ERROR = 'FILTRAR_PRODUCTOS_STOCK_ERROR';

export const OBTENER_PRODUCTO_STOCK_SELECCIONADO = 'OBTENER_PRODUCTO_STOCK_SELECCIONADO';
export const PRODUCTO_STOCK_SELECCIONADO_EXITO = 'PRODUCTO_STOCK_SELECCIONADO_EXITO';
export const PRODUCTO_STOCK_SELECCIONADO_ERROR = 'PRODUCTO_STOCK_SELECCIONADO_ERROR';
export const LIMPIAR_PRODUCTOS_STOCK = 'LIMPIAR_PRODUCTOS_STOCK';

export const CAMBIAR_STATUS_STOCK = 'CAMBIAR_STATUS_STOCK';

export const SELECCIONAR_PROVEDOR = 'SELECCIONAR_PROVEDOR';

export const SOLICITUD_DESDE_STOCK = 'SOLICITUD_DESDE_STOCK';
export const CAMBIO_MODAL = 'CAMBIO_MODAL';
export const DESCARGA_PRODUCTOS_PROVEDOR_STOCK_EXITO = 'DESCARGA_PRODUCTOS_PROVEDOR_STOCK_EXITO';
export const EDITAR_PRODUCTO_PROVEDOR = 'EDITAR_PRODUCTO_PROVEDOR';


// TYPES ARTICULOS

export const AGREGAR_ARTICULO = 'AGREGAR_ARTICULO';
export const AGREGAR_ARTICULO_EXITO = 'AGREGAR_ARTICULO_EXITO';
export const AGREGAR_ARTICULO_ERROR = 'AGREGAR_ARTICULO_ERROR';
export const COMENZAR_DESCARGA_ARTICULOS = 'COMENZAR_DESCARGA_ARTICULOS';
export const DESCARGA_ARTICULOS_EXITO = 'DESCARGA_ARTICULOS_EXITO';
export const DESCARGA_ARTICULOS_ERROR = 'DESCARGA_ARTICULOS_ERROR';
export const OBTENER_ARTICULO_ELIMINAR = 'OBTENER_ARTICULO_ELIMINAR';
export const ARTICULO_ELIMINADO_EXITO = 'ARTICULO_ELIMINADO_EXITO';
export const ARTICULO_ELIMINADO_ERROR = 'ARTICULO_ELIMINADO_ERROR';
export const OBTENER_ARTICULO_EDITAR = 'OBTENER_ARTICULO_EDITAR';
export const COMENZAR_EDICION_ARTICULO = 'COMENZAR_EDICION_ARTICULO';
export const ARTICULO_EDITADO_EXITO = 'ARTICULO_EDITADO_EXITO';
export const ARTICULO_EDITADO_ERROR = 'ARTICULO_EDITADO_ERROR';
export const FILTRAR_ARTICULOS_EXITO = 'FILTRAR_ARTICULOS_EXITO';
export const FILTRAR_ARTICULOS_ERROR = 'FILTRAR_ARTICULOS_ERROR';
export const OBTENER_ARTICULO_SELECCIONADO = 'OBTENER_ARTICULO_SELECCIONADO';
export const ARTICULO_SELECCIONADO_EXITO = 'ARTICULO_SELECCIONADO_EXITO';
export const ARTICULO_SELECCIONADO_ERROR = 'ARTICULO_SELECCIONADO_ERROR';
export const LIMPIAR_ARTICULOS = 'LIMPIAR_ARTICULOS';
export const AGREGAR_ORDEN_ID_ERROR = 'AGREGAR_ORDEN_ID_ERROR';
export const DATOS_BUSQUEDA = 'DATOS_BUSQUEDA';

//Types Sucursales
export const SUCURSAL_SELECCIONADA_EXITO = 'SUCURSAL_SELECCIONADA_EXITO';
export const SUCURSAL_SELECCIONADA_ERROR = 'SUCURSAL_SELECCIONADA_ERROR';
export const AGREGAR_SUCURSAL = 'AGREGAR_SUCURSAL';
export const ELIMINAR_SUCURSAL = 'ELIMINAR_SUCURSAL';
export const DESCARGA_SUCURSALES_STOCK_EXITO = 'DESCARGA_SUCURSALES_STOCK_EXITO';
export const DESCARGA_SUCURSALES_STOCK_ERROR = 'DESCARGA_SUCURSALES_STOCK_ERROR';
export const SUCURSAL_TRANSFERIR_EXITO = 'SUCURSAL_TRANSFERIR_EXITO';
export const DESCARGA_SUCURSALES_FILTER_EXITO = 'DESCARGA_SUCURSALES_FILTER_EXITO';
export const SUCURSAL_ACTIONS_EXITO = 'SUCURSAL_ACTIONS_EXITO';
export const SUCURSAL_EDITADA_EXITO = 'SUCURSAL_EDITADA_EXITO';
export const SUCURSAL_EDITADA_ERROR = 'SUCURSAL_EDITADA_ERROR';

//Types clientes
export const CLIENTE_SELECCIONADO_EXITO = 'CLIENTE_SELECCIONADO_EXITO';
export const CLIENTE_SELECCIONADO_ERROR = 'CLIENTE_SELECCIONADO_ERROR';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const DESCARGA_CLIENTES_EXITO = 'DESCARGA_CLIENTES_EXITO';
export const DESCARGA_CLIENTES_ERROR = 'DESCARGA_CLIENTES_ERROR';
export const CLIENTE_ACTIONS_EXITO = 'CLIENTE_ACTIONS_EXITO';
export const DESCARGA_CLIENTES_STOCK_ERROR = 'DESCARGA_CLIENTES_STOCK_ERROR';
export const CLIENTE_EDITADO_EXITO = 'CLIENTE_EDITADO_EXITO';
export const CLIENTE_EDITADO_ERROR = 'CLIENTE_EDITADO_ERROR';

//Types provedor
export const PROVEDOR_SELECCIONADO_EXITO = 'PROVEDOR_SELECCIONADO_EXITO';
export const PROVEDOR_SELECCIONADO_ERROR = 'PROVEDOR_SELECCIONADO_ERROR';
export const AGREGAR_PROVEDOR = 'AGREGAR_PROVEDOR';
export const DESCARGA_PROVEDORES_EXITO = 'DESCARGA_PROVEDORES_EXITO';
export const DESCARGA_PROVEDORES_ERROR = 'DESCARGA_PROVEDORES_ERROR';
export const PROVEDOR_ACTIONS_EXITO = 'PROVEDOR_ACTIONS_EXITO';
export const DESCARGA_PROVEDORES_STOCK_ERROR = 'DESCARGA_PROVEDORES_STOCK_ERROR';
export const PROVEDOR_EDITADO_EXITO = 'PROVEDOR_EDITADO_EXITO';
export const PROVEDOR_EDITADO_ERROR = 'PROVEDOR_EDITADO_ERROR';